default: &default
  api_key: <%= ENV.fetch("API_KEY") %> 
  users:
    -
      pipedrive_id: 2458634
      name: Igor B.
    -
      pipedrive_id: 312013
      name: Vitaliy B.
    -
      pipedrive_id: 2839466
      name: Anastasia I.

  plans:
    won_total: 120000
    new_deals: 80
    won_deals: 6


development:
  <<: *default


test:
  <<: *default

production:
  <<: *default
