default: &default
  api_key: <%= ENV.fetch("PIPEDRIVE_API_KEY") %> 
  users:
    -
      pipedrive_id: 312013
      name: Vitaliy B.
    -
      pipedrive_id: 11514576
      name: Roman K.

  plans:
    won_total: 223001
    new_deals: 80
    won_deals: 6


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
