default: &default
  api_key: <%= ENV.fetch("API_KEY") %> 
  users:
    -
      pipedrive_id: 2458634
      name: Igor B.
    -
      pipedrive_id: 312013
      name: Vitaliy B.
    -
      pipedrive_id: 2839466
      name: Anastasia I.
    -
      pipedrive_id: 4240239
      name: Dmitry S.

  plans:
    won_total: 0
    new_deals: 60
    won_deals: 5


development:
  <<: *default


test:
  <<: *default

production:
  <<: *default
